# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Eo8CifN2/1oT8SUsFmg6lCR8ynw/B85qx9rNAJKyUURFEnjAd8NH1a/MYyCc/++uzwiLxIvxXvLlmxCIihhOT3WsTOvMqUERHUGOb8GkvcT0pNiQ03WGtQHBiD2ZJjr6qADIkQy9Ua6Vu9lm2qPp+sl3EMAPCHFAwD//eskw4AoKaphRBkg5jjM9fY220lZQy3rCnswFMsGPMnNHLLYAIfX9G4tVLUKwEXFO7S5mITXENdSxwQeWhFICvLaqL7aT/YaNvlv71ZOWTUpl4r1e1J9xSc5Ja1WfGQTelmVd0JhR5T5Dd+hXhhqJHCfROerv/ddfFjDJWFFot3KL3YMtN+dslin77RYdU7ko+6U+PKlPSBW5ir8+JRYfm+L0FR/X+r7meZnSwbG98Apq45h9BvDR6T31iLlhsgcxSWakSwlMc+C+uE2iKeeCff/WNFzCPFbSsmCOJNpYaJ2kkRtdC65q8I//oWXTg1ns9BuqkKvslrXXG3NjdqQLzdh6lzebTM87kuWmCfxCf8o40+5tiuVyndy4VVRVI/EkwNllQUlKBG1PHQJtT2AYYsVlZIa/E8iKurMmmSMkBgChzyjlrvy6Mjz6n8QThN+nCLet4rejR98jl5yluW6TolFDa41VcPaoq5LmTFW0tFqPyM8siLbaeiJgbm9s+yfd1veQQ7w="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
