travis:
  secure:
    BINSTAR_TOKEN: Eo8CifN2/1oT8SUsFmg6lCR8ynw/B85qx9rNAJKyUURFEnjAd8NH1a/MYyCc/++uzwiLxIvxXvLlmxCIihhOT3WsTOvMqUERHUGOb8GkvcT0pNiQ03WGtQHBiD2ZJjr6qADIkQy9Ua6Vu9lm2qPp+sl3EMAPCHFAwD//eskw4AoKaphRBkg5jjM9fY220lZQy3rCnswFMsGPMnNHLLYAIfX9G4tVLUKwEXFO7S5mITXENdSxwQeWhFICvLaqL7aT/YaNvlv71ZOWTUpl4r1e1J9xSc5Ja1WfGQTelmVd0JhR5T5Dd+hXhhqJHCfROerv/ddfFjDJWFFot3KL3YMtN+dslin77RYdU7ko+6U+PKlPSBW5ir8+JRYfm+L0FR/X+r7meZnSwbG98Apq45h9BvDR6T31iLlhsgcxSWakSwlMc+C+uE2iKeeCff/WNFzCPFbSsmCOJNpYaJ2kkRtdC65q8I//oWXTg1ns9BuqkKvslrXXG3NjdqQLzdh6lzebTM87kuWmCfxCf8o40+5tiuVyndy4VVRVI/EkwNllQUlKBG1PHQJtT2AYYsVlZIa/E8iKurMmmSMkBgChzyjlrvy6Mjz6n8QThN+nCLet4rejR98jl5yluW6TolFDa41VcPaoq5LmTFW0tFqPyM8siLbaeiJgbm9s+yfd1veQQ7w=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
