travis:
  secure:
    BINSTAR_TOKEN: X0s4gRzoQ6kWk/p3CZWEhY/P/mkECEa922iVnW0hOxX3mrMgJ4BAuGABGHss8WptBlX1JJvC2PstQBW86qNa35u2h8qzbEGSasohzFnYqeVJPOp9dJYE+HTDprwEyDBWOYo7fVlZhP37mpYuOn3vdeouif69xJUL4SpfF4vHJ/yaC7NBOqzMYfZ9Qu5oWiadzdPy40YBEKDsr9o7z0J9Dw8F3ScUhN15k5egMiEU+cwa38/v9xJJV5vucez4W5shIVtUF3CjOsPP3wDsBCq11UENGhoejXNkQt9b/Joq3sJMVqY45J4532sM6y8fpQxc3UdfPfiwRWwyjRQ9VnZjNHFK3FP21B5yhvlP2aRa99GSUpr1FE/vTf2bDtWCeuohjNr2eYFwUkyo0nbGergVW1n2I8LnYFYNAczCaQRi8YUxdlQUlWCwehkZ486+B1otXDHqMWnCtCeS6GThv4KLFjBnxnql4y+CX0PrYWVxFh1v5/pU3NaDRR0PCAs3ci6wxqwEKpT0bDyi8LPSUmd3zx/VnN53pwCN6JM+98xauftjZgzSY24z+4HidKXvk0szWEfdL6XEmeF3fhjK5+xRiqit9PgFT+3D5ye4VqLuObtbmZ56NJHob03UFcOnQT0fpJYSQyjUhs7ay+9Uo8LjBrJUoK7mi+ngct/xj+lxUaE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
